using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TitanBot.Commands;

namespace TT2Bot
{
    public static partial class TT2Localisation
    {
        public static partial class Game
        {
            public static class HelperSkill
            {
                private const string BASE_PATH = Game.BASE_PATH + "HELPERSKILL_";
                
                public const string UNABLE_DOWNLOAD = BASE_PATH + nameof(UNABLE_DOWNLOAD);
                public const string MULTIPLE_MATCHES = BASE_PATH + nameof(MULTIPLE_MATCHES);
                public static LocalisedString GetName(int skillId)
                    => new LocalisedString(BASE_PATH + skillId.ToString());

                public static IReadOnlyDictionary<string, string> Defaults { get; }
                    = new Dictionary<string, string>
                    {
                        { UNABLE_DOWNLOAD, "I could not download any hero skill data. Please try again later." },
                        { MULTIPLE_MATCHES, "There were more than 1 hero skills that matched `{0}`" },
                        { GetName(1).Key, "Nature's Presence" },
                        { GetName(2).Key, "Lightning Rage" },
                        { GetName(3).Key, "Executioner's Breath" },
                        { GetName(4).Key, "Poison Touch" },
                        { GetName(5).Key, "Hidden Veil" },
                        { GetName(6).Key, "Paralysis" },
                        { GetName(7).Key, "Dynamic Force" },
                        { GetName(8).Key, "Superstition" },
                        { GetName(9).Key, "Ghost Breath" },
                        { GetName(10).Key, "Spectral Nova" },
                        { GetName(11).Key, "Brooding Thrill" },
                        { GetName(12).Key, "Guardian's Chant" },
                        { GetName(13).Key, "Soul Initiative" },
                        { GetName(14).Key, "Medusa's Strife" },
                        { GetName(15).Key, "Essence of Horn" },
                        { GetName(16).Key, "Command Ritual" },
                        { GetName(17).Key, "Tribal Vision" },
                        { GetName(18).Key, "Battle Thirst" },
                        { GetName(19).Key, "Royal Presence" },
                        { GetName(20).Key, "Relentless Force" },
                        { GetName(21).Key, "Unforgiving" },
                        { GetName(22).Key, "Stomping Presence" },
                        { GetName(23).Key, "Hammer Pulse" },
                        { GetName(24).Key, "Psychosis" },
                        { GetName(25).Key, "War Beacon" },
                        { GetName(26).Key, "Hammer Circle" },
                        { GetName(27).Key, "Battle Fortitude" },
                        { GetName(28).Key, "Steel Nerves" },
                        { GetName(29).Key, "Land Warrior" },
                        { GetName(30).Key, "Scythe Master" },
                        { GetName(31).Key, "Scorched Essence" },
                        { GetName(32).Key, "Winds of Clarity" },
                        { GetName(33).Key, "Death March" },
                        { GetName(34).Key, "Battle Brawler" },
                        { GetName(35).Key, "Winds of Calm" },
                        { GetName(36).Key, "Ruthless Pursuit" },
                        { GetName(37).Key, "Cloud of Justice" },
                        { GetName(38).Key, "Merciless" },
                        { GetName(39).Key, "Devilish Charmer" },
                        { GetName(40).Key, "Dungeon Trapper" },
                        { GetName(41).Key, "Custom Machinery" },
                        { GetName(42).Key, "Methodically Manic" },
                        { GetName(43).Key, "Sphinx Presence" },
                        { GetName(44).Key, "Panther's Touch" },
                        { GetName(45).Key, "Copper Skin" },
                        { GetName(46).Key, "Special Fighter" },
                        { GetName(47).Key, "Skull Cap" },
                        { GetName(48).Key, "Master Manipulator" },
                        { GetName(49).Key, "Perpetual Impulsivity" },
                        { GetName(50).Key, "Arthur's Revenge" },
                        { GetName(51).Key, "Call of the Relic" },
                        { GetName(52).Key, "Circle of Atonement" },
                        { GetName(53).Key, "Enchanted Veil" },
                        { GetName(54).Key, "Traveller" },
                        { GetName(55).Key, "Relentless" },
                        { GetName(56).Key, "The Sword's Path" },
                        { GetName(57).Key, "Blunt Strength" },
                        { GetName(58).Key, "Viking Slash Force" },
                        { GetName(59).Key, "Rune Enabler" },
                        { GetName(60).Key, "Bearded Fortitude" },
                        { GetName(61).Key, "Spirit Vessel" },
                        { GetName(62).Key, "Essence of Valhalla" },
                        { GetName(63).Key, "Warrior Loyalty" },
                        { GetName(64).Key, "Bolt Block Brigade" },
                        { GetName(65).Key, "Analog Cloud" },
                        { GetName(66).Key, "Strength in Numbers" },
                        { GetName(67).Key, "Tough as Bolts" },
                        { GetName(68).Key, "Steel Heart" },
                        { GetName(69).Key, "Battle Spirit" },
                        { GetName(70).Key, "Thrill of the Fight" },
                        { GetName(71).Key, "Blunt Brutality" },
                        { GetName(72).Key, "Dungeon Loyalty" },
                        { GetName(73).Key, "Meteor Wave" },
                        { GetName(74).Key, "Dreadful Disintegration" },
                        { GetName(75).Key, "Gruesome Ritual" },
                        { GetName(76).Key, "Sacrifice" },
                        { GetName(77).Key, "Circle of Death" },
                        { GetName(78).Key, "Nature's Revenge" },
                        { GetName(79).Key, "Hydra Force" },
                        { GetName(80).Key, "Death Flight" },
                        { GetName(81).Key, "Animal Advantage" },
                        { GetName(82).Key, "Vitality" },
                        { GetName(83).Key, "Charcoal Screen" },
                        { GetName(84).Key, "Dark Veil" },
                        { GetName(85).Key, "Silver Rider" },
                        { GetName(86).Key, "Guiding Chant" },
                        { GetName(87).Key, "Cloacked Rebel" },
                        { GetName(88).Key, "Activism" },
                        { GetName(89).Key, "Beacon of Hope" },
                        { GetName(90).Key, "Haunting Barrage" },
                        { GetName(91).Key, "Spirit Harvest" },
                        { GetName(92).Key, "Hawk Clutch" },
                        { GetName(93).Key, "Wind Speed" },
                        { GetName(94).Key, "Ancient Flight" },
                        { GetName(95).Key, "Aerial Advantage" },
                        { GetName(96).Key, "Winged Commander" },
                        { GetName(97).Key, "Vision Walk" },
                        { GetName(98).Key, "Wrath of the Relics" },
                        { GetName(99).Key, "Emerald Deception" },
                        { GetName(100).Key, "Demon's Heart" },
                        { GetName(101).Key, "Nature's Presence" },
                        { GetName(102).Key, "Lightning Rage" },
                        { GetName(103).Key, "Executioner's Breath" },
                        { GetName(104).Key, "Poison Touch" },
                        { GetName(105).Key, "Hidden Veil" },
                        { GetName(106).Key, "Paralysis" },
                        { GetName(107).Key, "Dynamic Force" },
                        { GetName(108).Key, "Superstition" },
                        { GetName(109).Key, "Ghost Breath" },
                        { GetName(110).Key, "Spectral Nova" },
                        { GetName(111).Key, "Brooding Thrill" },
                        { GetName(112).Key, "Guardian's Chant" },
                        { GetName(113).Key, "Soul Initiative" },
                        { GetName(114).Key, "Medusa's Strife" },
                        { GetName(115).Key, "Essence of Horn" },
                        { GetName(116).Key, "Command Ritual" },
                        { GetName(117).Key, "Tribal Vision" },
                        { GetName(118).Key, "Battle Thirst" },
                        { GetName(119).Key, "Royal Presence" },
                        { GetName(120).Key, "Relentless Force" },
                        { GetName(121).Key, "Unforgiving" },
                        { GetName(122).Key, "Stomping Presence" },
                        { GetName(123).Key, "Hammer Pulse" },
                        { GetName(124).Key, "Psychosis" },
                        { GetName(125).Key, "War Beacon" },
                        { GetName(126).Key, "Hammer Circle" },
                        { GetName(127).Key, "Battle Fortitude" },
                        { GetName(128).Key, "Steel Nerves" },
                        { GetName(129).Key, "Land Warrior" },
                        { GetName(130).Key, "Scythe Master" },
                        { GetName(131).Key, "Scorched Essence" },
                        { GetName(132).Key, "Winds of Clarity" },
                        { GetName(133).Key, "Death March" },
                        { GetName(134).Key, "Battle Brawler" },
                        { GetName(135).Key, "Winds of Calm" },
                        { GetName(136).Key, "Ruthless Pursuit" },
                        { GetName(137).Key, "Cloud of Justice" },
                        { GetName(138).Key, "Merciless" },
                        { GetName(139).Key, "Devilish Charmer" },
                        { GetName(140).Key, "Dungeon Trapper" },
                        { GetName(141).Key, "Custom Machinery" },
                        { GetName(142).Key, "Methodically Manic" },
                        { GetName(143).Key, "Sphinx Presence" },
                        { GetName(144).Key, "Panther's Touch" },
                        { GetName(145).Key, "Copper Skin" },
                        { GetName(146).Key, "Special Fighter" },
                        { GetName(147).Key, "Skull Cap" },
                        { GetName(148).Key, "Master Manipulator" },
                        { GetName(149).Key, "Perpetual Impulsivity" },
                        { GetName(150).Key, "Arthur's Revenge" },
                        { GetName(151).Key, "Call of the Relic" },
                        { GetName(152).Key, "Circle of Atonement" },
                        { GetName(153).Key, "Enchanted Veil" },
                        { GetName(154).Key, "Traveller" },
                        { GetName(155).Key, "Relentless" },
                        { GetName(156).Key, "The Sword's Path" },
                        { GetName(157).Key, "Blunt Strength" },
                        { GetName(158).Key, "Viking Slash Force" },
                        { GetName(159).Key, "Rune Enabler" },
                        { GetName(160).Key, "Bearded Fortitude" },
                        { GetName(161).Key, "Spirit Vessel" },
                        { GetName(162).Key, "Essence of Valhalla" },
                        { GetName(163).Key, "Warrior Loyalty" },
                        { GetName(164).Key, "Bolt Block Brigade" },
                        { GetName(165).Key, "Analog Cloud" },
                        { GetName(166).Key, "Strength in Numbers" },
                        { GetName(167).Key, "Tough as Bolts" },
                        { GetName(168).Key, "Steel Heart" },
                        { GetName(169).Key, "Battle Spirit" },
                        { GetName(170).Key, "Thrill of the Fight" },
                        { GetName(171).Key, "Blunt Brutality" },
                        { GetName(172).Key, "Dungeon Loyalty" },
                        { GetName(173).Key, "Meteor Wave" },
                        { GetName(174).Key, "Dreadful Disintegration" },
                        { GetName(175).Key, "Gruesome Ritual" },
                        { GetName(176).Key, "Sacrifice" },
                        { GetName(177).Key, "Circle of Death" },
                        { GetName(178).Key, "Nature's Revenge" },
                        { GetName(179).Key, "Hydra Force" },
                        { GetName(180).Key, "Death Flight" },
                        { GetName(181).Key, "Animal Advantage" },
                        { GetName(182).Key, "Vitality" },
                        { GetName(183).Key, "Charcoal Screen" },
                        { GetName(184).Key, "Dark Veil" },
                        { GetName(185).Key, "Silver Rider" },
                        { GetName(186).Key, "Guiding Chant" },
                        { GetName(187).Key, "Cloacked Rebel" },
                        { GetName(188).Key, "Activism" },
                        { GetName(189).Key, "Beacon of Hope" },
                        { GetName(190).Key, "Haunting Barrage" },
                        { GetName(191).Key, "Spirit Harvest" },
                        { GetName(192).Key, "Hawk Clutch" },
                        { GetName(193).Key, "Wind Speed" },
                        { GetName(194).Key, "Ancient Flight" },
                        { GetName(195).Key, "Aerial Advantage" },
                        { GetName(196).Key, "Winged Commander" },
                        { GetName(197).Key, "Vision Walk" },
                        { GetName(198).Key, "Wrath of the Relics" },
                        { GetName(199).Key, "Emerald Deception" },
                        { GetName(200).Key, "Demon's Heart" },
                        { GetName(201).Key, "Nature's Presence" },
                        { GetName(202).Key, "Lightning Rage" },
                        { GetName(203).Key, "Executioner's Breath" },
                        { GetName(204).Key, "Poison Touch" },
                        { GetName(205).Key, "Hidden Veil" },
                        { GetName(206).Key, "Paralysis" },
                        { GetName(207).Key, "Dynamic Force" },
                        { GetName(208).Key, "Superstition" },
                        { GetName(209).Key, "Ghost Breath" },
                        { GetName(210).Key, "Spectral Nova" },
                        { GetName(211).Key, "Brooding Thrill" },
                        { GetName(212).Key, "Guardian's Chant" },
                        { GetName(213).Key, "Soul Initiative" },
                        { GetName(214).Key, "Medusa's Strife" },
                        { GetName(215).Key, "Essence of Horn" },
                        { GetName(216).Key, "Command Ritual" },
                        { GetName(217).Key, "Tribal Vision" },
                        { GetName(218).Key, "Battle Thirst" },
                        { GetName(219).Key, "Royal Presence" },
                        { GetName(220).Key, "Relentless Force" },
                        { GetName(221).Key, "Unforgiving" },
                        { GetName(222).Key, "Stomping Presence" },
                        { GetName(223).Key, "Hammer Pulse" },
                        { GetName(224).Key, "Psychosis" },
                        { GetName(225).Key, "War Beacon" },
                        { GetName(226).Key, "Hammer Circle" },
                        { GetName(227).Key, "Battle Fortitude" },
                        { GetName(228).Key, "Steel Nerves" },
                        { GetName(229).Key, "Land Warrior" },
                        { GetName(230).Key, "Scythe Master" },
                        { GetName(231).Key, "Scorched Essence" },
                        { GetName(232).Key, "Winds of Clarity" },
                        { GetName(233).Key, "Death March" },
                        { GetName(234).Key, "Battle Brawler" },
                        { GetName(235).Key, "Winds of Calm" },
                        { GetName(236).Key, "Ruthless Pursuit" },
                        { GetName(237).Key, "Cloud of Justice" },
                        { GetName(238).Key, "Merciless" },
                        { GetName(239).Key, "Devilish Charmer" },
                        { GetName(240).Key, "Dungeon Trapper" },
                        { GetName(241).Key, "Custom Machinery" },
                        { GetName(242).Key, "Methodically Manic" },
                        { GetName(243).Key, "Sphinx Presence" },
                        { GetName(244).Key, "Panther's Touch" },
                        { GetName(245).Key, "Copper Skin" },
                        { GetName(246).Key, "Special Fighter" },
                        { GetName(247).Key, "Skull Cap" },
                        { GetName(248).Key, "Master Manipulator" },
                        { GetName(249).Key, "Perpetual Impulsivity" },
                        { GetName(250).Key, "Arthur's Revenge" },
                        { GetName(251).Key, "Call of the Relic" },
                        { GetName(252).Key, "Circle of Atonement" },
                        { GetName(253).Key, "Enchanted Veil" },
                        { GetName(254).Key, "Traveller" },
                        { GetName(255).Key, "Relentless" },
                        { GetName(256).Key, "The Sword's Path" },
                        { GetName(257).Key, "Blunt Strength" },
                        { GetName(258).Key, "Viking Slash Force" },
                        { GetName(259).Key, "Rune Enabler" },
                        { GetName(260).Key, "Bearded Fortitude" },
                        { GetName(261).Key, "Spirit Vessel" },
                        { GetName(262).Key, "Essence of Valhalla" },
                        { GetName(263).Key, "Warrior Loyalty" },
                        { GetName(264).Key, "Bolt Block Brigade" },
                        { GetName(265).Key, "Analog Cloud" },
                        { GetName(266).Key, "Strength in Numbers" },
                        { GetName(267).Key, "Tough as Bolts" },
                        { GetName(268).Key, "Steel Heart" },
                        { GetName(269).Key, "Battle Spirit" },
                        { GetName(270).Key, "Thrill of the Fight" },
                        { GetName(271).Key, "Blunt Brutality" },
                        { GetName(272).Key, "Dungeon Loyalty" },
                        { GetName(273).Key, "Meteor Wave" },
                        { GetName(274).Key, "Dreadful Disintegration" },
                        { GetName(275).Key, "Gruesome Ritual" },
                        { GetName(276).Key, "Sacrifice" },
                        { GetName(277).Key, "Circle of Death" },
                        { GetName(278).Key, "Nature's Revenge" },
                        { GetName(279).Key, "Hydra Force" },
                        { GetName(280).Key, "Death Flight" },
                        { GetName(281).Key, "Animal Advantage" },
                        { GetName(282).Key, "Vitality" },
                        { GetName(283).Key, "Charcoal Screen" },
                        { GetName(284).Key, "Dark Veil" },
                        { GetName(285).Key, "Silver Rider" },
                        { GetName(286).Key, "Guiding Chant" },
                        { GetName(287).Key, "Cloacked Rebel" },
                        { GetName(288).Key, "Activism" },
                        { GetName(289).Key, "Beacon of Hope" },
                        { GetName(290).Key, "Haunting Barrage" },
                        { GetName(291).Key, "Spirit Harvest" },
                        { GetName(292).Key, "Hawk Clutch" },
                        { GetName(293).Key, "Wind Speed" },
                        { GetName(294).Key, "Ancient Flight" },
                        { GetName(295).Key, "Aerial Advantage" },
                        { GetName(296).Key, "Winged Commander" },
                        { GetName(297).Key, "Vision Walk" },
                        { GetName(298).Key, "Wrath of the Relics" },
                        { GetName(299).Key, "Emerald Deception" },
                        { GetName(300).Key, "Demon's Heart" },
                        { GetName(301).Key, "Nature's Presence" },
                        { GetName(302).Key, "Lightning Rage" },
                        { GetName(303).Key, "Executioner's Breath" },
                        { GetName(304).Key, "Poison Touch" },
                        { GetName(305).Key, "Hidden Veil" },
                        { GetName(306).Key, "Paralysis" },
                        { GetName(307).Key, "Dynamic Force" },
                        { GetName(308).Key, "Superstition" },
                        { GetName(309).Key, "Ghost Breath" },
                        { GetName(310).Key, "Spectral Nova" },
                        { GetName(311).Key, "Brooding Thrill" },
                        { GetName(312).Key, "Guardian's Chant" },
                        { GetName(313).Key, "Soul Initiative" },
                        { GetName(314).Key, "Medusa's Strife" },
                        { GetName(315).Key, "Essence of Horn" },
                        { GetName(316).Key, "Command Ritual" },
                        { GetName(317).Key, "Tribal Vision" },
                        { GetName(318).Key, "Battle Thirst" },
                        { GetName(319).Key, "Royal Presence" },
                        { GetName(320).Key, "Relentless Force" },
                        { GetName(321).Key, "Unforgiving" },
                        { GetName(322).Key, "Stomping Presence" },
                        { GetName(323).Key, "Hammer Pulse" },
                        { GetName(324).Key, "Psychosis" },
                        { GetName(325).Key, "War Beacon" },
                        { GetName(326).Key, "Hammer Circle" },
                        { GetName(327).Key, "Battle Fortitude" },
                        { GetName(328).Key, "Steel Nerves" },
                        { GetName(329).Key, "Land Warrior" },
                        { GetName(330).Key, "Scythe Master" },
                        { GetName(331).Key, "Scorched Essence" },
                        { GetName(332).Key, "Winds of Clarity" },
                        { GetName(333).Key, "Death March" },
                        { GetName(334).Key, "Battle Brawler" },
                        { GetName(335).Key, "Winds of Calm" },
                        { GetName(336).Key, "Ruthless Pursuit" },
                        { GetName(337).Key, "Cloud of Justice" },
                        { GetName(338).Key, "Merciless" },
                        { GetName(339).Key, "Devilish Charmer" },
                        { GetName(340).Key, "Dungeon Trapper" },
                        { GetName(341).Key, "Custom Machinery" },
                        { GetName(342).Key, "Methodically Manic" },
                        { GetName(343).Key, "Sphinx Presence" },
                        { GetName(344).Key, "Panther's Touch" },
                        { GetName(345).Key, "Copper Skin" },
                        { GetName(346).Key, "Special Fighter" },
                        { GetName(347).Key, "Skull Cap" },
                        { GetName(348).Key, "Master Manipulator" },
                        { GetName(349).Key, "Perpetual Impulsivity" },
                        { GetName(350).Key, "Arthur's Revenge" },
                        { GetName(351).Key, "Call of the Relic" },
                        { GetName(352).Key, "Circle of Atonement" },
                        { GetName(353).Key, "Enchanted Veil" },
                        { GetName(354).Key, "Traveller" },
                        { GetName(355).Key, "Relentless" },
                        { GetName(356).Key, "The Sword's Path" },
                        { GetName(357).Key, "Blunt Strength" },
                        { GetName(358).Key, "Viking Slash Force" },
                        { GetName(359).Key, "Rune Enabler" },
                        { GetName(360).Key, "Bearded Fortitude" },
                        { GetName(361).Key, "Spirit Vessel" },
                        { GetName(362).Key, "Essence of Valhalla" },
                        { GetName(363).Key, "Warrior Loyalty" },
                        { GetName(364).Key, "Bolt Block Brigade" },
                        { GetName(365).Key, "Analog Cloud" },
                        { GetName(366).Key, "Strength in Numbers" },
                        { GetName(367).Key, "Tough as Bolts" },
                        { GetName(368).Key, "Steel Heart" },
                        { GetName(369).Key, "Battle Spirit" },
                        { GetName(370).Key, "Thrill of the Fight" }
                    }.ToImmutableDictionary();
            }
        }
    }
}
